language: node_js
node_js:
- stable
branches:
  only:
  - master
deploy:
  edge: true
  skip_cleanup: true
  provider: npm
  email: at@webhouse.dk
  api_key:
    secure: cSSBzLb6dvOVGUjHqcw2zWWIvLSajsmS8Qaf/gmr0bn1p0AGFfPow0OWRfnS0gJsOU8jN4h0gQZvZUbNvOmjjwWFjWMsFeCWtxWrNt1pI9KIeCv8II64JS4g5g66dR9vPnppx94pNJZu6zx8UdiLzsyyms6ZT1hhtQelNDawq6LU+SyEkKKiFaKQn8En/CAGwHGTLXX4iQLnJ4v9ReRJ3Jrrt+kEUxMbvc4y3YQKJ4osMMgv7LZxTLSsj7HFx/oKwaCEtXLqWG/FD7KufTPUAUb3A+kPp7nMwqiZ7+UzS0TMJSkq43FNOXdzxZZjU/ibbcpuvXkERMe6CdVc8ZW2ytAnjnUcm+GDA61txzahr5G7+HkQ211aExm4Q5Jg/na3KzQU7UmV9swVRPr6LQipIzVuf/k9CS3BkRWswlc670YeN+SGb1r0XfrtyDnL4SjYFeX6WkigUw0y7ZtkrlsJKwywj/SHHWBo21TpBlurHfVf2hU9118FlhsVwXKM1nRQnC59rTCYOn/JgkCJHuA1UojSdvNzFv4IZ0OL1o1hutWE54uQ5uPVzTE+MSHg/OCUqB4q15uRY7Lr+xaD2h3gYppxhUXQrLX7nHpuoO2nZ933dX4OWGgyVEmolvz0AAbZtDMMqS5CvbrMZHmPMsbPXkb5gHFJgYJu1vsFMs3Mh2I=
  on:
    repo: senti-iot/senti-apicore
notifications:
  email:
    recipients:
    - cb@webhouse.dk
    on_success: never
    on_failure: always
  slack:
    secure: gUnGuVhbj1X7VoOx1zEELFNq4vNFY0UyawuEb8/V2y7dubwr9N11g/vR1dVO0v07W/K1gWctx6tttxdytJTGcRYvF7IdMOrGPzRdXx/prUOOuW8oonMRV4CGYxzf28dzFxIdpWqmrjJn4CpY8vzZxM/eeOTngaVMfCi/PhdYhS741udZOt7l3QDXJ1T2abcvogPMTwpAT6GLCrl58tHv5y0zKIEfvjeTI0Ixb6IvYKKYcwvEBWhzLu43/6HOPrHNHnvK9luOXPW7a0eTSK1GHsSEErQxW869/N1it99Fld5tQTWiwbB0XlE0vn39Bv8Dx1j8Y5Bvr2tXQJZwRUCFL5OAoNDOSZVjQc1Pv61apZfMClN+9ywJhZmPSx+8SSsOkrDtCD1rbIDCO/IvoksmxTxh1adCBe0hmvHVDtohCmbyD5PlCNAtu2WYJt0yGAEngwEF5ph5B/elIRuMOO8MY0boRze/qBivneyLA95yqOFsn4e3Lfbp0kI5l9i+HGarItoa5XGUDYFoGPDRPmJBW4RtVTIe0F/PVw3h6bweNSwN4hzaWjWsXApTzhFJIJibUSqiOBbJ207HCG5fq73HWbF8OCxz+7XmtbNncxi7HY4KkKEjzi+kNplKW5KuR8S5wwwuhpAlsvGN0liCRmSaNrKof6ufAW1eCUZBphnAPpM=
